#spring.datasource.url=jdbc:mysql://localhost:3306/sgt-ep
#spring.datasource.username=root
#spring.datasource.password=admin
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=create-drop
###spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#
#spring.main.allow-bean-definition-overriding=true
#spring.main.allow-circular-references=true
#logging.level.org.springframework.security=DEBUG
###spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
###spring.security.user.name=user
###spring.security.user.password=1234